import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,cpSync,readFileSync,writeFileSync,mkdirSync,rmSync,linkSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {checkArtifact,checkWorkflow} from '../../scripts/check-showcase.mjs';
const root=path.resolve(import.meta.dirname,'../..'),output=path.join(root,'showcase/dist');
const revision=()=>JSON.parse(readFileSync(path.join(output,'revision.json'),'utf8')).commit;
function rejects(change,pattern){const dir=mkdtempSync(path.join(tmpdir(),'nova-showcase-check-'));try{cpSync(output,dir,{recursive:true});change(dir);assert.throws(()=>checkArtifact(dir,{expectedRevision:revision(),repositoryRoot:root}),pattern);}finally{rmSync(dir,{recursive:true,force:true});}}
test('actual public artifact and workflow satisfy project-base, revision, notices and isolated deployment',()=>{checkArtifact(output,{expectedRevision:revision(),repositoryRoot:root});checkWorkflow(readFileSync(path.join(root,'.github/workflows/pages.yml'),'utf8'));});
test('private path and source map cannot enter output',()=>{rejects(dir=>{mkdirSync(path.join(dir,'.sdcorejs'));writeFileSync(path.join(dir,'.sdcorejs','log.txt'),'private');},/allowlist/);rejects(dir=>writeFileSync(path.join(dir,'assets','leak.js.map'),'{}'),/allowlist/);});
test('hardlinked artifact file is rejected even with an allowed filename',()=>{rejects(dir=>{const asset=readdirSync(path.join(dir,'assets')).find(f=>f.endsWith('.js'));linkSync(path.join(dir,'assets',asset),path.join(dir,'assets','hardlink.js'));},/hardlink/);});
test('revision accepts only exact public metadata and asset keys',()=>{for(const extra of [false,true])rejects(dir=>{const f=path.join(dir,'revision.json'),data=JSON.parse(readFileSync(f,'utf8'));if(extra)data.assets[0].comment='extra';else data.comment='extra';writeFileSync(f,JSON.stringify(data));},/metadata/);});
test('root-relative and encoded traversal assets are rejected',()=>{for(const asset of ['/assets/bad.js','/sdcorejs-nova/assets/%2e%2e/bad.js'])rejects(dir=>{const f=path.join(dir,'index.html');writeFileSync(f,readFileSync(f,'utf8').replace(/\/sdcorejs-nova\/assets\/[^" ]+\.js/,asset));},/asset|path|base/);});
test('revision mismatch and malformed revision fail',()=>{rejects(dir=>writeFileSync(path.join(dir,'revision.json'),JSON.stringify({commit:'a'.repeat(40)})),/revision/);rejects(dir=>writeFileSync(path.join(dir,'revision.json'),JSON.stringify({commit:'unknown'})),/revision/);});
test('dirty local preview metadata cannot pass deployment checks',()=>{const dir=mkdtempSync(path.join(tmpdir(),'nova-showcase-dirty-'));try{cpSync(output,dir,{recursive:true});const file=path.join(dir,'revision.json'),metadata=JSON.parse(readFileSync(file,'utf8'));metadata.workingTreeDirty=true;writeFileSync(file,JSON.stringify(metadata));assert.throws(()=>checkArtifact(dir,{expectedRevision:revision(),repositoryRoot:root,requireClean:true}),/dirty/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('bundle licenses and private transfer/source strings are checked',()=>{rejects(dir=>writeFileSync(path.join(dir,'THIRD_PARTY_BUNDLE_LICENSES.md'),'React'),/license/);rejects(dir=>{const f=path.join(dir,'index.html');writeFileSync(f,readFileSync(f,'utf8')+'<!-- Sentinel_private signed_transfer_url -->');},/private|forbidden/);});
test('removing an entire transitive license section cannot evade bundle inventory validation',()=>{rejects(dir=>{const f=path.join(dir,'THIRD_PARTY_BUNDLE_LICENSES.md');writeFileSync(f,readFileSync(f,'utf8').replace(/## scheduler - [\s\S]*?(?=\n## |$)/,''));},/license inventory/);});
test('workflow rejects write-all, missing browser gate and always-upload',()=>{const text=readFileSync(path.join(root,'.github/workflows/pages.yml'),'utf8');assert.throws(()=>checkWorkflow(text.replace('permissions:\n  contents: read','permissions: write-all')),/permission/);assert.throws(()=>checkWorkflow(text.replace('      - name: Showcase production browser checks\n        run: npm run test:showcase\n','')),/gate|order/);assert.throws(()=>checkWorkflow(text.replace('      - name: Upload checked static artifact only','      - name: Upload checked static artifact only\n        if: always()')),/conditional|upload|step/);});
test('workflow cannot skip required checks through echo shell or default execution overrides',()=>{const text=readFileSync(path.join(root,'.github/workflows/pages.yml'),'utf8');assert.throws(()=>checkWorkflow(text.replace('        run: npm run test:showcase','        run: npm run test:showcase\n        shell: echo {0}')),/modifier/);assert.throws(()=>checkWorkflow(text.replace('jobs:','defaults:\n  run:\n    shell: echo {0}\n\njobs:')),/modifier/);});
test('Pages workflow rejects permission escalation, missing read permission, unpinned action and non-main dispatch',()=>{const text=readFileSync(path.join(root,'.github/workflows/pages.yml'),'utf8');assert.throws(()=>checkWorkflow(text.replace('contents: read','contents: write')),/permission/);assert.throws(()=>checkWorkflow(text.replace('pages: read','pages: none')),/permission/);assert.throws(()=>checkWorkflow(text.replace(/actions\/checkout@[a-f0-9]{40}/,'actions/checkout@main')),/pin/);assert.throws(()=>checkWorkflow(text.replaceAll("if: github.ref == 'refs/heads/main'",'if: always()')),/main/);});
// The positive case reads the actual build. Mutations are isolated temporary
// copies, deleted by rejects(); they never alter the approved source/artifact.
